export const AllProduct = [
  {
    id: 1,
    itemNum: 'MTA1231',
    pname: '菱格花紋簍空感綁帶針織洋裝',
    price: 1090,
    image: [
      '/images/product/pd1-1-1.jpg',
      '/images/product/pd1-1-2.jpg',
      '/images/product/pd1-1-3.jpg',
      '/images/product/pd1-1-4.jpg',
      '/images/product/pd1-1-5.jpg',
      '/images/product/pd1-1-6.jpg',
    ],
    color: '米杏色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 2,
    itemNum: 'MTA1232',
    pname: '菱格花紋簍空感綁帶針織洋裝',
    price: 1090,
    image: [
      '/images/product/pd1-2-1.jpg',
      '/images/product/pd1-2-2.jpg',
      '/images/product/pd1-2-3.jpg',
      '/images/product/pd1-2-4.jpg',
      '/images/product/pd1-2-5.jpg',
      '/images/product/pd1-2-6.jpg',
    ],
    color: '淺藍色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 3,
    itemNum: 'MTA1241',
    pname: '簍空感透肌POLO上衣',
    price: 690,
    image: ['/images/product/pd8-1.jpg'],
    color: '米杏色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 4,
    itemNum: 'MTA1242',
    pname: '簍空感透肌POLO上衣',
    price: 690,
    image: ['/images/product/pd8-2.jpg'],

    color: '綠色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 5,
    itemNum: 'MTA1251',
    pname: '慵懶皺皺感削肩洋裝',
    price: 990,
    image: [
      '/images/product/pd2-1-1.jpg',
      '/images/product/pd2-1-2.jpg',
      '/images/product/pd2-1-3.jpg',
      '/images/product/pd2-1-4.jpg',
      '/images/product/pd2-1-5.jpg',
      '/images/product/pd2-1-6.jpg',
      '/images/product/pd2-1-7.jpg',
    ],
    color: '淺灰色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 6,
    itemNum: 'MTA1252',
    pname: '慵懶皺皺感削肩洋裝',
    price: 990,
    image: [
      '/images/product/pd2-2-1.jpg',
      '/images/product/pd2-2-2.jpg',
      '/images/product/pd2-2-3.jpg',
      '/images/product/pd2-2-4.jpg',
      '/images/product/pd2-2-5.jpg',
      '/images/product/pd2-2-6.jpg',
    ],
    color: '淺藍色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 7,
    itemNum: 'MTA1253',
    pname: '慵懶皺皺感削肩洋裝',
    price: 990,
    image: [
      '/images/product/pd2-3-1.jpg',
      '/images/product/pd2-3-2.jpg',
      '/images/product/pd2-3-3.jpg',
      '/images/product/pd2-3-4.jpg',
      '/images/product/pd2-3-5.jpg',
      '/images/product/pd2-3-6.jpg',
    ],
    color: '米橘色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 8,
    itemNum: 'MTA1261',
    pname: '舒適純棉短版背心',
    price: 450,
    image: ['/images/product/pd6-3.jpg'],
    color: '杏灰色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 9,
    itemNum: 'MTA1262',
    pname: '舒適純棉短版背心',
    price: 450,
    image: ['/images/product/pd6-1.jpg'],
    color: '白色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 10,
    itemNum: 'MTA1263',
    pname: '舒適純棉短版背心',
    price: 450,
    image: ['/images/product/pd6-2.jpg'],
    color: '綠色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 11,
    itemNum: 'MTA1271',
    pname: '抽繩口袋造型工裝裙',
    price: 850,
    image: ['/images/product/pd7-1.jpg'],
    color: '鐵灰色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 12,
    itemNum: 'MTA1272',
    pname: '抽繩口袋造型工裝裙',
    price: 850,
    image: ['/images/product/pd7-2.jpg'],
    color: '杏色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 13,
    itemNum: 'MTA1281',
    pname: '側開岔寬鬆印花素TEE',
    price: 590,
    image: ['/images/product/pd5-1.jpg'],
    color: '米色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 14,
    itemNum: 'MTA1282',
    pname: '側開岔寬鬆印花素TEE',
    price: 590,
    image: ['/images/product/pd5-2.jpg'],
    color: '藍色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
  {
    id: 15,
    itemNum: 'MTA1283',
    pname: '側開岔寬鬆印花素TEE',
    price: 590,
    image: ['/images/product/pd5-3.jpg'],
    color: '綠色',
    size: ['S', 'M', 'L'],
    event: '新品上架限時95折',
    discount: 0.05,
  },
];

export const category = [
  '上身 | Tops',
  '下身 | Bottoms',
  '外套 | Outerwears',
  '連身 | Dress & jumpsuits',
  '飾品 | Accessories',
  '現貨 | In stock',
];

export const OrderHistory = [
  {
    No: 2025050200021,
    date: '20250502',
    sum: 2660,
    state: ['已完成', '20250525'],
  },
  {
    No: 2025051600156,
    date: '20250516',
    sum: 1285,
    state: ['已完成', '20250603'],
  },
  {
    No: 2025052400093,
    date: '20250524',
    sum: 2350,
    state: ['處理中'],
  },
];
